project: kaggle-zzz
group: test2
wandb: True
series_data_path: ~/kaggle-zzz/data/small_data/Zzzs_train.parquet
events_data_path: ~/kaggle-zzz/data/raw_data/train_events.csv
# num_workers: 2

params:
  seed: 42
  n_splits: 4
  batch_size: 32
  epochs: 2
  learning_rate: 0.01
  patience: 10
  hidden_dim: 8
  num_layers: 1

features:
  - enmo
  - anglez

targets:
  - onset_heatmap
  - wakeup_heatmap

hydra:
  run:
    dir: outputs/${project}